DROP TABLE IF EXISTS kek;
DROP SEQUENCE IF EXISTS kek_seq;
CREATE TABLE IF NOT EXISTS kek
(
    id          INTEGER PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL,
    description VARCHAR(200) NOT NULL
);
CREATE SEQUENCE IF NOT EXISTS kek_seq START WITH 1 INCREMENT BY 1;
ALTER SEQUENCE kek_seq INCREMENT BY 1;